version: 2.1
jobs:
  build:
    environment:
      - CI: true # Used by karma.conf.js to determine whether or not to use a headless browser.
    docker:
      - image: cimg/node:20.2.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            - dependency-cache-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: npm run test
workflows:
  version: 2
  build:
    jobs:
      - build
