version: 2.1
jobs:
  build:
    environment:
      - CI: true # Used by karma.conf.js to determine whether or not to use a headless browser.
    docker:
      - image: cimg/node:20.2.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            - dependency-cache-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
          name: Install Google Chrome
          command: |
            sudo apt-get update
            sudo apt-get install -y wget --no-install-recommends
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable --no-install-recommends
      - run:
          name: Run tests
          command: npm run test
workflows:
  version: 2
  build:
    jobs:
      - build
